version: "3"

services:
  cache-house:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8080"
    volumes:
      - ./go.mod:/src/go.mod
      - ./go.sum:/src/go.sum
      - ./cmd:/src/cmd
      - ./internal:/src/internal
      - ./.env.example:/src/.env.example
    networks:
      - default
      - tc-advertising3_default
networks:
  default:
  tc-advertising3_default:
    external: true
