apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-house
  namespace: rtb
spec:
  replicas: 1
  selector:
    matchLabels:
      repository: cache-house
  template:
    metadata:
      labels:
        repository: cache-house
    spec:
      containers:
      - name: cache-house
        image: gcr.io/clickadilla/cache-house:v0.1
        envFrom:
          - secretRef:
              name: cache-house
#      nodeSelector:
#        cloud.google.com/gke-nodepool: worker-pool
